version: 2
  jobs:
    test:
      docker:
        - image: circleci/node:18.12
      steps:
        - checkout
        - run: echo "Running tests"
        - run: npm install
        - run: npm test
    coverage:
      docker:
        - image: circleci/node:18.12
      steps:
        - checkout
        - run: echo "Running coverage test"
        - run: npm install
        - run: npm coverage
    build:
      docker:
        - image: circleci/node:18.12
      steps:
        - checkout
        - run: echo "build project"
        - npm install
        - npm run build

workflows:
  version: 2
    test_build:
      jobs:
        - test
        - build:
          requires:
            - test
