
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - run: echo "build project"
      - npm install
      - npm run build

workflows:
  test_build:
    jobs:
      - test
      - build

